=== edleyrocha/protocolmining/trunk/IP_stream/IP_stream/appConfig/connStringConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 sp2 (http://www.altova.com) by SHOCK (SHOCK) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 sp2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="connectionStrings">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="add" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="configSections"/>
				<xs:element ref="connectionStrings"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="configSections">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="add"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="add">
		<xs:complexType>
			<xs:attribute name="providerName" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="System.Data.OracleClient"/>
						<xs:enumeration value="System.Data.SqlClient"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="MSSQL"/>
						<xs:enumeration value="Oracle"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="connectionString" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== edleyrocha/protocolmining/trunk/IP_stream/IP_stream/bin/Debug/connStringConfig.xml
<?xml version="1.0" encoding="utf-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="G:\protocolmining\IP_stream\IP_stream\appConfig\connStringConfig.xsd">
	<LocalDatabaseConn>
		<add connectionString="Data Source=192.168.2.104;Initial Catalog=IP_stream;Persist Security Info=True;User ID=sa;Password=1234" name="192.168.2.104_IP_stream" />
		<add connectionString="new Name" name="new Name" />
		<add connectionString="new Name" name="new Name" />
	</LocalDatabaseConn>
	<RemoteDatabaseConn>
		<add connectionString="Data Source=192.168.2.104;Initial Catalog=tt;Persist Security Info=True;User ID=sa;Password=1234" name="192.168.2.104_tt" />
		<add connectionString="new Name" name="new Name" />
		<add connectionString="new Name" name="new Name" />
	</RemoteDatabaseConn>
	<InsertDatabaseConn>
		<add connectionString="Data Source=192.168.2.104;Initial Catalog=tt;Persist Security Info=True;User ID=sa;Password=1234" name="192.168.2.104_tt" />
		<add connectionString="new Name" name="new Name" />
		<add connectionString="new Name" name="new Name" />
		<add connectionString="new Name" name="new Name" />
	</InsertDatabaseConn>
	<DatabaseConnPool xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
		<add name="localhost_test" connectionString="Data Source=localhost;Initial Catalog=test;User ID=sa;password=sa;" providerName="System.Data.SqlClient" />
		<add name="TEST_sa" connectionString="Data Source=TEST;User ID=sa;Password=sa;" providerName="System.Data.OracleClient" />
		<add name="192.168.1.17_sz_17a_20100818_18" connectionString="Data Source=192.168.1.17;Initial Catalog=sz_17a_20100818_18;Persist Security Info=True;User ID=sa;Password=sa" providerName="System.Data.SqlClient" />
		<add name="localhost_ip_stream" connectionString="Data Source=localhost;Initial Catalog=ip_stream;Integrated Security=True" providerName="System.Data.SqlClient" />
		<add name="192.168.1.12_IP_stream_23a_20100524_new" connectionString="Data Source=192.168.1.12;Initial Catalog=IP_stream_23a_20100524_new;Persist Security Info=True;User ID=sa;Password=sa" providerName="System.Data.SqlClient" />
		<add name=".\sqlexpress_|DataDirectory|\Database.mdf" connectionString="Data Source=.\sqlexpress;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True;User Instance=True" providerName="System.Data.SqlClient" />
		<add name=".\SQLEXPRESS_ip_stream" connectionString="Data Source=.\SQLEXPRESS;Initial Catalog=ip_stream;Integrated Security=True" providerName="System.Data.SqlClient" />
		<add name="192.168.1.17_sz_23A_20100524_11" connectionString="Data Source=192.168.1.17;Initial Catalog=sz_23A_20100524_11;Persist Security Info=True;User ID=sa;Password=sa" providerName="System.Data.SqlClient" />
		<add connectionString="Data Source=192.168.1.17;Initial Catalog=sz_23A_20100524_11;Persist Security Info=True;User ID=sa;Password=sa" name="192.168.1.17_sz_23A_20100524_11" />
		<add connectionString="Data Source=.\SQLEXPRESS;Initial Catalog=ip_stream;Integrated Security=True" name=".\SQLEXPRESS_ip_stream" />
		<add connectionString="new Name" name="new Name" />
		<add connectionString="new Name" name="new Name" />
	</DatabaseConnPool>
</configuration>

=== edleyrocha/protocolmining/trunk/IP_stream/IP_stream/appConfig/connStringConfig.xml
<?xml version="1.0" encoding="utf-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="G:\protocolmining\IP_stream\IP_stream\appConfig\connStringConfig.xsd">
  <configSections>
    <add name="localhost_test" connectionString="Data Source=localhost;Initial Catalog=test;User ID=sa;password=sa;" providerName="System.Data.SqlClient" />
  </configSections>
  <connectionStrings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <add name="localhost_test" connectionString="Data Source=localhost;Initial Catalog=test;User ID=sa;password=sa;" providerName="System.Data.SqlClient" />
    <add name="TEST_sa" connectionString="Data Source=TEST;User ID=sa;Password=sa;" providerName="System.Data.OracleClient" />
    <add name="192.168.1.17_sz_17a_20100818_18" connectionString="Data Source=192.168.1.17;Initial Catalog=sz_17a_20100818_18;Persist Security Info=True;User ID=sa;Password=sa" providerName="System.Data.SqlClient" />
    <add name="localhost_ip_stream" connectionString="Data Source=localhost;Initial Catalog=ip_stream;Integrated Security=True" providerName="System.Data.SqlClient" />
    <add name="192.168.1.12_IP_stream_23a_20100524_new" connectionString="Data Source=192.168.1.12;Initial Catalog=IP_stream_23a_20100524_new;Persist Security Info=True;User ID=sa;Password=sa" providerName="System.Data.SqlClient" />
    <add name=".\sqlexpress_|DataDirectory|\Database.mdf" connectionString="Data Source=.\sqlexpress;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True;User Instance=True" providerName="System.Data.SqlClient" />
    <add name=".\SQLEXPRESS_ip_stream" connectionString="Data Source=.\SQLEXPRESS;Initial Catalog=ip_stream;Integrated Security=True" providerName="System.Data.SqlClient" />
    <add name="192.168.1.17_sz_23A_20100524_11" connectionString="Data Source=192.168.1.17;Initial Catalog=sz_23A_20100524_11;Persist Security Info=True;User ID=sa;Password=sa" providerName="System.Data.SqlClient" />
  </connectionStrings>
  <connectionStrings>
    <connectionString>Data Source=192.168.1.17;Initial Catalog=sz_17a_20100818_18;Persist Security Info=True;User ID=sa;Password=sa</connectionString>
    <DateTime>2010-12-24T16:55:50.203125+08:00</DateTime>
  </connectionStrings>
  <connectionStrings>
    <connectionString>Data Source=192.168.1.17;Initial Catalog=sz_23A_20100524_11;Persist Security Info=True;User ID=sa;Password=sa</connectionString>
    <DateTime>2010-12-24T16:56:00.390625+08:00</DateTime>
  </connectionStrings>
</configuration>
