=== edleyrocha/protocolmining/IP_stream/IP_stream/appConfig/streamTypeDefine.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2008 rel. 2 sp2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="url">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value=".3gp"/>
				<xs:enumeration value=".avi"/>
				<xs:enumeration value=".mp3"/>
				<xs:enumeration value=".swf"/>
				<xs:enumeration value=".zip"/>
				<xs:enumeration value="PPLive"/>
				<xs:enumeration value="PPStream"/>
				<xs:enumeration value="QVOD"/>
				<xs:enumeration value="UUSee"/>
				<xs:enumeration value="ad.3g.net.cn"/>
				<xs:enumeration value="cctvbox.cctv.com"/>
				<xs:enumeration value="cjis.cn"/>
				<xs:enumeration value="farm*qq.com"/>
				<xs:enumeration value="feidiantv"/>
				<xs:enumeration value="ggmusic.3g.cn"/>
				<xs:enumeration value="hexin"/>
				<xs:enumeration value="http"/>
				<xs:enumeration value="imupdate.3g.cn"/>
				<xs:enumeration value="kaixin.com"/>
				<xs:enumeration value="kugou.com"/>
				<xs:enumeration value="lark"/>
				<xs:enumeration value="live.qq.com"/>
				<xs:enumeration value="liveja.amigo."/>
				<xs:enumeration value="ltmp3.cn"/>
				<xs:enumeration value="mail."/>
				<xs:enumeration value="mmsc.monternet.com"/>
				<xs:enumeration value="mmsservice"/>
				<xs:enumeration value="qqmusic"/>
				<xs:enumeration value="tv.video.sina.com.cn"/>
				<xs:enumeration value="video"/>
				<xs:enumeration value="wap.haoting."/>
				<xs:enumeration value="wap.ttpod."/>
				<xs:enumeration value="xunlei.com"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="uris">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="url" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="BrowseCategory"/>
						<xs:enumeration value="GameCategory"/>
						<xs:enumeration value="GeneralDownloads"/>
						<xs:enumeration value="IM"/>
						<xs:enumeration value="MMS"/>
						<xs:enumeration value="P2P"/>
						<xs:enumeration value="StockCategory"/>
						<xs:enumeration value="StreamingMedia"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="ports">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="port" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="GameCategory"/>
						<xs:enumeration value="IM"/>
						<xs:enumeration value="MMS"/>
						<xs:enumeration value="StockCategory"/>
						<xs:enumeration value="StreamingMedia"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="port">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="14000"/>
				<xs:enumeration value="211.136.107.88"/>
				<xs:enumeration value="211.136.163.36"/>
				<xs:enumeration value="211.136.165.57"/>
				<xs:enumeration value="211.136.221.125"/>
				<xs:enumeration value="211.138.100.244"/>
				<xs:enumeration value="211.139.144.145"/>
				<xs:enumeration value="211.94.156.162"/>
				<xs:enumeration value="211.99.191.229"/>
				<xs:enumeration value="218.200.160.29"/>
				<xs:enumeration value="218.204.254.237"/>
				<xs:enumeration value="222.73.34.172"/>
				<xs:enumeration value="222.73.34.5"/>
				<xs:enumeration value="222.73.34.8"/>
				<xs:enumeration value="61.145.124.185"/>
				<xs:enumeration value="6666"/>
				<xs:enumeration value="6667"/>
				<xs:enumeration value="8040"/>
				<xs:enumeration value="9901"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="TcpPortType">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ports" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="StreamIdentification">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="TcpPortType"/>
				<xs:element ref="HttpWspUriType"/>
				<xs:element ref="ResponseType"/>
				<xs:element ref="ProtocolType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Responses">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Response" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="StreamingMedia"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="ResponseType">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Responses"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Response">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="audio"/>
				<xs:enumeration value="multipart"/>
				<xs:enumeration value="video"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Protocols">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Protocol" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="GeneralDownloads"/>
						<xs:enumeration value="IM"/>
						<xs:enumeration value="MMS"/>
						<xs:enumeration value="P2P"/>
						<xs:enumeration value="StreamingMedia"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="ProtocolType">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Protocols" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Protocol">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="BitTorrent"/>
				<xs:enumeration value="MMSE"/>
				<xs:enumeration value="eDonkey"/>
				<xs:enumeration value="ftp"/>
				<xs:enumeration value="oicq"/>
				<xs:enumeration value="pop"/>
				<xs:enumeration value="pop3"/>
				<xs:enumeration value="rtsp"/>
				<xs:enumeration value="smtp"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="HttpWspUriType">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="uris" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== edleyrocha/protocolmining/IP_stream/IP_stream/bin/Debug/streamTypeDefine.xml
<?xml version="1.0" encoding="utf-8"?>
<StreamIdentification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="G:\protocolmining\IP_stream\IP_stream\appConfig\streamTypeDefine.xsd">
	<!--端口识别-->
	<!--ip地址根据uri识别的地址池反转-->
	<TcpPortType>
		<ports name="IM">
			<port>14000</port>
			<port>8040</port>
			<port>211.99.191.229</port>
			<port>13001</port>
			<port>4701</port>
		</ports>
		<ports name="GameCategory">
			<!--？不确定<port>13001</port>-->
			<port>6666</port>
			<port>6667</port>
			<port>6668</port>
			<port>9901</port>
			<port>211.136.163.36</port>
		</ports>
		<ports name="StreamingMedia">
			<port>211.136.165.57</port>
			<port>218.204.254.237</port>
			<port>218.200.160.29</port>
		</ports>
		<ports name="MMS">
			<port>211.94.156.162</port>
			<port>211.139.144.145</port>
			<port>211.136.221.125</port>
			<port>211.138.100.244</port>
			<port>218.201.200.5</port>
		</ports>
		<ports name="StockCategory">
			<port>61.145.124.185</port>
			<port>222.73.34.5</port>
			<port>222.73.34.8</port>
			<port>222.73.34.172</port>
			<port>211.136.107.88</port>
		</ports>
	</TcpPortType>
	<!--URI识别-->
	<HttpWspUriType>
		<uris name="P2P">
			<url>xunlei.com</url>
			<url>kugou.com</url>
			<url>PPLive</url>
			<url>PPStream</url>
			<url>live.qq.com</url>
			<url>UUSee</url>
			<url>QVOD</url>
			<url>tv.video.sina.com.cn</url>
			<url>cctvbox.cctv.com</url>
			<url>feidiantv</url>
		</uris>
		<uris name="StreamingMedia">
			<url>ggmusic.3g.cn</url>
			<url>ad.3g.net.cn</url>
			<url>imupdate.3g.cn</url>
			<url>qqmusic</url>
			<url>lark</url>
			<url>video</url>
			<url>wap.ttpod.</url>
			<url>wap.haoting.</url>
			<url>ltmp3.cn</url>
		</uris>	
		<uris name="GeneralDownloads">
			<url>.mp4</url>
			<url>.mp3</url>
			<url>.avi</url>
			<url>.zip</url>
			<url>.swf</url>
			<url>.3gp</url>
			<url>.exe</url>
			<url>.sis</url>
			<url>.sisx</url>
			<url>.rar</url>
			<url>.jar</url>
			<url>.cab</url> 
		</uris>
		<uris name="IM">
			<url>liveja.amigo.</url>
			<url>http://10.0.0.172:80/transfer.vurl?guid=%</url>
			<url>119.147.</url>
			<url>121.14.</url>
			<url>211.137.</url>
			<url>211.139.</url>
			<url>221.130.</url>
		</uris>
		<uris name="MMS">
			<url>mmsservice</url>
			<url>mmsc.monternet.com</url>
			<url>mmsc.</url>
		</uris>
		<uris name="GameCategory">
			<url>farm*qq.com</url>
			<url>kaixin.com</url>
		</uris>
		<uris name="StockCategory">
			<url>hexin</url>
			<url>cjis.cn</url>
			<url>61.160.219.55:80</url>
			<url>:2345</url>
			<url>:12346</url>
		</uris>
		<uris name="BrowseCategory">
			<!--邮件类？？？-->
			<url>mail.</url>
			<url>218.204.255.90</url>
			<url>http</url>
		</uris>
	</HttpWspUriType>
	<!--response识别-->
	<ResponseType>
		<Responses name="StreamingMedia">
			<Response>video</Response>
			<Response>audio</Response>
			<Response>multipart</Response>
		</Responses>
	</ResponseType>
	<!--协议识别-->
	<ProtocolType>
		<Protocols name="P2P">
			<Protocol>BitTorrent</Protocol>
			<Protocol>eDonkey</Protocol>
		</Protocols>
		<Protocols name="StreamingMedia">
			<Protocol>rtsp</Protocol>
		</Protocols>
		<Protocols name="MMS">
			<Protocol>MMSE</Protocol>
		</Protocols>
		<Protocols name="GeneralDownloads">
			<Protocol>ftp</Protocol>
		</Protocols>
		<Protocols name="BrowseCategory">
		<!--邮件类？？？-->
			<Protocol>smtp</Protocol>
			<Protocol>pop</Protocol>
			<Protocol>pop3</Protocol>
		</Protocols>
		<Protocols name="IM">
			<Protocol>oicq</Protocol>
		</Protocols>
	</ProtocolType>
</StreamIdentification>
